### ISSUE TITLE
Error While Publishing the Angular Application

### ISSUE THREAD

**Issue by LaserStony** [dfa1234/ng2-simple-crypt#3]
I ran `npm build --prod` and got this. I hope you look into it..
```
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask th
em to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (APPlication_PATH\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:749:23)
    at plugin.done.then (APPlication_PATH\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)


```

**Comment by dfa1234** [comment]
It's something new to angular 6.
Did you run `npm build --prod` into your project or into this project?

**Comment by LaserStony** [comment]
I ran `npm build --prod` into my main Project or aka App..

**Comment by LaserStony** [comment]
so @dfa1234 , Any help on this...? I am unable to build the Application for production... and Am Seriously in a bind. Hope that you can Solve this issue ASAP.
*Note: Every Library that I was using was latest with angular-cli at ^6.latest... (not 7)

**Comment by dfa1234** [comment]
Yes it's because of the new packaging system in angular 6
It's bother me what they are doing. I will correct it soon (I have several libraries in this case)
Meanwhile please remove the library with `npm uninstall` this library and use this file in you project:
https://github.com/dfa1234/ngx-simple-crypt/blob/master/index.ts
